name: CI Workflow
on:
  workflow_dispatch:
    name: on-demand
    inputs:
      ENV:
        type: choice
        required: true
        options:
          - qa
          - ct
          - prod
        default: "qa"
        description: "Environment"
      BROWSER:
        type: choice
        required: true
        options:
          - chrome
          - firefox
          - edge
        default: "chrome"
        description: "Browser"
      HEADLESS:
        type: choice
        required: true
        options:
          - true
          - false
        default: "true"
        description: "Headless mode"
      TAGS:
        required: true
        description: 'Cucumber tags to run'
        default: '@login'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: "123.0.6312.122"
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "124.0.2"
      - name: Set up Microsoft Edge
        uses: browser-actions/setup-edge@latest
        with:
          edge-version: "123.0.2420.81"
      - name: Test run
        run: |
          mvn clean test -Denv=${{ github.event.inputs.ENV }} -Dbrowser=${{ github.event.inputs.BROWSER }} -Dheadless=${{ github.event.inputs.HEADLESS }} -Dcucumber.filter.tags="${{ github.event.inputs.TAGS }}"

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-reports
          path: /target/cucumber-reports
          retention-days: 1