name: CI Workflow
on:
  workflow_dispatch:
    name: on-demand
    inputs:
      ENV:
        type: choice
        required: true
        options:
          - qa
          - ct
          - prod
        default: "qa"
        description: "Environment"
      BROWSER:
        type: choice
        required: true
        options:
          - chrome
          - firefox
          - edge
        default: "chrome"
        description: "Browser"
      HEADLESS:
        type: choice
        required: true
        options:
          - true
          - false
        default: "true"
        description: "Headless mode"
      TAGS:
        required: true
        description: 'Cucumber tags to run'
        default: '@login'

env:
  CHROME_VERSION: "123.0.6312.105"
  FIREFOX_VERSION: "124.0.2"
  EDGE_VERSION: "stable"

jobs:
  test-info:
    runs-on: ubuntu-latest
    steps:
      - name: Tests Running Information
        run: |
          echo "### Tests Running Summary :zap:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch tag:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Test scenario tags:** ${{ github.event.inputs.TAGS }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ github.event.inputs.ENV }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Browser:** ${{ github.event.inputs.BROWSER }} with version: ${{ github.event.inputs.BROWSER == 'chrome' && env.CHROME_VERSION || (github.event.inputs.BROWSER == 'firefox' && env.FIREFOX_VERSION || env.EDGE_VERSION) }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Headless Mode:** ${{ github.event.inputs.HEADLESS }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
  test-run:
    needs: test-info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Setup Browser
        run: |
          if [ "${{ github.event.inputs.BROWSER }}" = "chrome" ]; then
            echo "Setting up Chrome browser"
            wget -qO- https://raw.githubusercontent.com/browser-actions/setup-chrome@latest/setup.sh | bash -s -- --version "${{ env.CHROME_VERSION }}"
          elif [ "${{ github.event.inputs.BROWSER }}" = "firefox" ]; then
            echo "Setting up Firefox browser"
            wget -qO- https://raw.githubusercontent.com/browser-actions/setup-firefox@latest/setup.sh | bash -s -- --version "${{ env.FIREFOX_VERSION }}"
          elif [ "${{ github.event.inputs.BROWSER }}" = "edge" ]; then
            echo "Setting up Edge browser"
            wget -qO- https://raw.githubusercontent.com/browser-actions/setup-edge@latest/setup.sh | bash -s -- --version "${{ env.EDGE_VERSION }}"
          else
            echo "Unsupported browser specified."
            exit 1
          fi
      - name: Test run
        run: |
          mvn clean test -Denv=${{ github.event.inputs.ENV }} -Dbrowser=${{ github.event.inputs.BROWSER }} -Dheadless=${{ github.event.inputs.HEADLESS }} -Dcucumber.filter.tags="${{ github.event.inputs.TAGS }}"
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-reports
          path: target/cucumber-reports
          retention-days: 1